name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Push Image to Artifact Registry
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: notely-473308
      GCP_REGION: us-central1
      AR_REPOSITORY: notely-ar-repo
      IMAGE_NAME: notely
      IMAGE_TAG: latest
      # finaler Artifact-Registry-Tag:
      IMAGE_URI: us-central1-docker.pkg.dev/notely-473308/notely-ar-repo/notely:latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Make build script executable
        run: chmod +x ./scripts/buildprod.sh

      - name: Build production binary (Linux target)
        run: ./scripts/buildprod.sh

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and push image via Cloud Build
        run: |
          gcloud builds submit \
            --project ${{ env.GCP_PROJECT_ID }} \
            --tag ${{ env.IMAGE_URI }} \
            .
